package com.example.assignmentapp.ui.theme

import androidx.compose.ui.graphics.Color

val LightPrimary = Color(0xFF006A6A)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFF9CF1F0)
val LightOnPrimaryContainer = Color(0xFF002020)
val LightSecondary = Color(0xFF4A6363)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFCCE8E7)
val LightOnSecondaryContainer = Color(0xFF051F1F)
val LightTertiary = Color(0xFF4B607C)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFD3E4FF)
val LightOnTertiaryContainer = Color(0xFF041C35)
val LightBackground = Color(0xFFF5FAF9)
val LightOnBackground = Color(0xFF171D1D)
val LightSurface = Color(0xFFF5FAF9)
val LightOnSurface = Color(0xFF171D1D)
val LightSurfaceVariant = Color(0xFFDAE5E4)
val LightOnSurfaceVariant = Color(0xFF3F4948)
val LightOutline = Color(0xFF6F7978)
val LightOutlineVariant = Color(0xFFBEC9C8)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)

val DarkPrimary = Color(0xFF80D5D4)
val DarkOnPrimary = Color(0xFF003737)
val DarkPrimaryContainer = Color(0xFF004F4F)
val DarkOnPrimaryContainer = Color(0xFF9CF1F0)
val DarkSecondary = Color(0xFFB0CCCB)
val DarkOnSecondary = Color(0xFF1B3534)
val DarkSecondaryContainer = Color(0xFF324B4A)
val DarkOnSecondaryContainer = Color(0xFFCCE8E7)
val DarkTertiary = Color(0xFFB3C7E9)
val DarkOnTertiary = Color(0xFF1B314B)
val DarkTertiaryContainer = Color(0xFF334863)
val DarkOnTertiaryContainer = Color(0xFFD3E4FF)
val DarkBackground = Color(0xFF0E1414)
val DarkOnBackground = Color(0xFFDEE4E3)
val DarkSurface = Color(0xFF0E1414)
val DarkOnSurface = Color(0xFFDEE4E3)
val DarkSurfaceVariant = Color(0xFF3F4948)
val DarkOnSurfaceVariant = Color(0xFFBEC9C8)
val DarkOutline = Color(0xFF899392)
val DarkOutlineVariant = Color(0xFF3F4948)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
